### ISSUE TITLE
Multi-kill Mines + Suicide

### ISSUE THREAD

**Issue by allejo** [allejo/UselessMine#2]
Two issues reported by thrak

> the major issue that i am noticing atm is that %minecount% seems to be incrementing with each kill
> there also seems to be an issue with scoring when owner kills more than a single player with same mine but that second issue seems more related to the server WW kill... 
> 
> other item i noticed is suicide kill: when owner and victim both killed by mine. seems victim score should decrement -1 and owner score should be unchanged (+1 for kill, -1 for suicide... this is for single enemy only) however both scores are decremented -1

**Comment by allejo** [comment]
Can someone observe to see if these issues still occur? This plug-in is loaded on ahs3's Paradise Valley (I think that's the name) and Urban Jungle.

**Comment by TheGiraffe3** [comment]
Do you still need help with this?..
